backend:
  name: github
  repo: KimberleaH/necropolisNails
  branch: main # Branch to update (optional; defaults to master)
  site_domain: https://necropolisnails.pages.dev/
  base_url: https://necropolisnails.pages.dev/
  auth_endpoint: /auth # This points to /functions/auth.js

media_folder: "/static/images" # Folder where user uploaded files should go
public_folder: "/images"


# The below needs to be updated...

collections:
  - name: 'home'
    label: 'Home'
    folder: 'content'
    slug: '{{slug}}'
    delete: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }

      ############# NAV LINKS #############
      - label: 'Nav Links'
        name: 'navlinks'
        widget: 'list'
        delete: true
        fields:
        - { label: 'Text', name: 'text', widget: 'string' }
        - { label: 'URL', name: 'link', widget: 'string' }

      ############# BOOKING BUTTON #############
      - { label: 'Text', name: 'bookBtnTxt', widget: 'string' }
      - { label: 'URL', name: 'bookBtnLnk', widget: 'string' }

      ############# HERO SECTION #############
      - { label: 'Main Heading', name: 'hero', widget: 'string' }
      - { label: 'Header Blurb', name: 'heroBlurb', widget: 'text' }
      - { label: 'Header Image', name: 'heroImg', widget: 'image' }
      - { label: 'Text', name: 'galleryBtnTxt', widget: 'string' }
      - { label: 'URL', name: 'galleryBtnlnk', widget: 'string' }

      ############# CONTACT SECTION #############
      - { label: 'Address', name: 'address', widget: 'string' }
      - { label: 'GMB URL', name: 'addressURL', widget: 'string' }
      - { label: 'Phone', name: 'phone', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string' }
      - { label: 'Instagram', name: 'instagram', widget: 'string', hint: 'This appears below the gallery.' }
      
      - label: 'Business Hours' ############# HOURS
        name: 'businessHours'
        widget: 'list'
        hint: 'Use <br> to create a gap.'
        delete: true
        fields:
        - { label: 'Days', name: 'days', widget: 'string' }
        - { label: 'Hours', name: 'hours', widget: 'string' }
        
      ############# ABOUT SECTION #############
      - { label: 'About Heading', name: 'about', widget: 'string' }
      - { label: 'About Blurb', name: 'aboutBlurb', widget: 'text' }

      ############# SERVICES BULLETS #############
      - label: 'Services'
        name: 'services'
        widget: 'list'
        delete: true
        fields:
        - { label: 'Service', name: 'service', widget: 'string' }

      ############# ACCOMODATIONS BULLETS #############
      - label: 'Accomodations'
        name: 'accomodations'
        widget: 'list'
        delete: true
        fields:
        - { label: 'Accomodation', name: 'accom', widget: 'string' }

      ############# GALLERY SECTION #############
      - label: 'Gallery'
        name: 'gallery'
        widget: 'list'
        delete: true
        fields:
        - { label: 'Image', name: 'image', widget: 'image' }
    